# -*- coding: utf-8 -*-
"""student.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFB2cFKUSA1QkaSWq9FzQqrQpwNlVFbm
"""

pip install faker

from faker import Faker

fake = Faker()

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()
np.random.seed(42)

n = 250

data = pd.DataFrame({
    "Student_ID": np.arange(1, n+1),
    "Name": [fake.name() for _ in range(n)],
    "Gender": np.random.choice(["Male", "Female"], n),
    "Department": np.random.choice(["CSE", "IT", "ECE"], n),
    "Year": np.random.choice(["1st", "2nd", "3rd"], n),
    "Maths": np.random.randint(60, 100, n),
    "Science": np.random.randint(50, 100, n),
    "English": np.random.randint(40, 100, n),
    "Attendance (%)": np.random.randint(40, 101, n),
    "Internal Marks": np.random.randint(2, 26, n)
})

print(data.head())

print(data.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

plt.figure()
sns.histplot(data['Maths'], kde=True)
plt.title("Maths Marks Distribution")
plt.show()

plt.figure()
sns.histplot(data['Science'], kde=True)
plt.title("Science Marks Distribution")
plt.show()

plt.figure()
sns.histplot(data['English'], kde=True)
plt.title("English Marks Distribution")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.boxplot(x=data['Maths'])
plt.title("Maths Boxplot")
plt.show()

plt.figure()
sns.boxplot(x=data['Attendance (%)'])
plt.title("Attendance Boxplot")
plt.show()

plt.figure()
sns.barplot(x='Department', y='Maths', data=data)
plt.title("Avg Maths by Department")
plt.show()

plt.figure()
sns.scatterplot(x='Maths', y='Science', data=data)
plt.title("Maths vs Science")
plt.show()

plt.figure()
sns.scatterplot(x='Attendance (%)', y='Maths', data=data)
plt.title("Attendance vs Maths")
plt.show()

sns.pairplot(data)
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(data.corr(numeric_only=True), annot=True)
plt.title("Correlation Heatmap")
plt.show()

plt.figure()
sns.lineplot(x='Student_ID', y='Maths', data=data)
plt.title("Maths Trend")
plt.show()